location_names: 
  - L0
  - L1
  - L2
  - L3

L0: { 
  x: 0.20,
  y: 0.40,
  z: .30, 
  r: 0.08, 
}
L1: { 
  x: 0.0,
  y: 0.40,
  z: .30,
  r: 0.08, 
}
L2: { 
  x: 0.50,
  y: 0.40,
  z: .30, 
  r: 0.08, 
}
L3: { 
  x: 0.30,
  y: -0.30,
  z: .30, 
  r: 0.08, 
}
location_orientation_types:
  - up_x
  - up_x 
  - up_x
  - up_x