location_names: 
  - L0
  - L1
  - L2
  - L3

L0: { # Left 
  x: 0.20,
  y: 0.40,
  z: .70, #0.08,
  r: 0.08, 
}
L1: { # Middle
  x: 0.0,
  y: 0.40,
  z: .70, #0.08,
  r: 0.08, 
}
L2: { # Right
  x: -0.20,
  y: 0.40,
  z: .07, #0.08,
  r: 0.08, 
}
L3: { # xtra space L
  x: 0.30,
  y: -0.30,
  z: .70, #0.08,
  r: 0.08, 
}
L4: { # xtra space R
  x: -0.30,
  y: -0.30,
  z: .70, #0.08,
  r: 0.08, 
}
location_orientation_types:
  - up_x
  - up_x 
  - up_x
  - up_x
  - up_x