location_names: 
  - L0
  - L1
  - L2
  - L3
#  - L4
#  - L5
L0_point: { # Leftmost
  x: 0.4,
  y: 0.45,
  z: 0.1,
  r: 0.05, # Detection radius (only needed for use with com node)
}
L1_point: { # Mid left
  x: 0.20,
  y: 0.45,
  z: 0.1,
  r: 0.05, 
}
L2_point: { # Middle
  x: 0.0,
  y: 0.45,
  z: 0.1,
  r: 0.05, 
}
L3_point: { # Mid right
  x: -0.20,
  y: 0.45,
  z: 0.1,
  r: 0.05, 
}
L4_point: { # Rightmost
  x: -0.4,
  y: 0.45,
  z: 0.1,
  r: 0.05, 
}
L5_point: { # xtra space
  x: 0.45,
  y: 0.0,
  z: 0.1,
  r: 0.05, 
}
location_orientation_types:
  - up
  - up 
  - up
  - up
  - up
  - up
obj_group:
  - blueBox_1
  - blueBox_2
  - pinkBox_1
  #- pinkBox_2
  #- greenBox_1
init_obj_locations:
  - L0
  - L1
  - L2