location_names: 
  - "left_base"
  - "right_base"
  - "top"
  - "side"

left_base: { 
  x: 0.30,
  y: 0.20,
  z: 0.15, 
  r: 0.08, 
}

right_base: { 
  x: 0.30,
  y: -0.20,
  z: 0.15, 
  r: 0.08, 
}

top: { 
  x: 0.30,
  y: 0.00,
  z: 0.33, 
  r: 0.08, 
}

side: { 
  x: 0.00,
  y: 0.50,
  z: 0.10, 
  r: 0.20, 
}

location_orientation_types:
  - up_x
  - up_x 
  - side_x
  - up_y