location_names: 
  - BL
  - BR
  - T
  - X
  - san
  - drop
  - drop2
BL_point: { # Left base
  x: -0.37,
  y: 0.25,
  z: 0.08,
  r: 0.05, # Detection radius (only needed for use with com node)
}
BR_point: { # Right base
  x: -0.53,
  y: 0.25,
  z: 0.08,
  r: 0.05, 
}
T_point: { # Top
  x: -0.45,
  y: 0.25,
  z: 0.19,
  r: 0.05, 
}
X_point: { # xtra space
  x: -0.30,
  y: -0.50,
  z: 0.08,
  r: 0.05, 
}
san_point: { # sanitation bin
  x: 0.0,
  y: 0.36,
  z: 0.08,
  r: 0.05, 
}
drop_point: { # drop off
  x: 0.40,
  y: 0.16,
  z: 0.25,
  r: 0.25, 
}
drop2_point: { # drop off
  x: 0.40,
  y: 0.25,
  z: 0.25,
  r: 0.25, 
}
#drop3_point: { # drop
#  x: 0.40,
#  y: 0.35,
#  z: 0.25,
#  r: 0.25, 
#}

location_orientation_types:
  - up_x
  - up_x 
  - side_x
  - up_x
  - up_x
  - up_x
  - up_x
obj_group:
  - blueBox_1
  - greenBox_1
  - pinkBox_1
init_obj_locations:
  - BL
  - BR
  - T