# Object ID for releasing; NOTE: Leave this blank to automatically detect the attached object and release it
string obj_id
---
# Properties about the physical movement of the robot
taskit/MovementProperties mv_props