location_names: 
  - "Else_1"
  - "Else_2"
  - "Else_3"
  - "l0"
  - "l1"
  - "l2"
  - "l3"
  - "l6"
  - "l7"
  - "l8"
  - "l9"
  - "Ready"

### REady position

Ready: {
  default: {
    x: 0.31,
    y: 0,
    z: 0.46,
  },
  detection_radius: 0.10, 
  orientation_type: up_x
}

### else location where A1 and A2 are placed and I_1 is placed
Else_1: {
  default: {
    x: 0.40,
    y: 0.10,
    z: 0.03, 
  },
  detection_radius: 0.10, 
  orientation_type: up_x
}

Else_2: {
  default: {
    x: 0.60,
    y: 0.10,
    z: 0.03, 
  },
  detection_radius: 0.10,
  orientation_type: up_x
}


Else_3: {
  default: {
    x: 0.50,
    y: 0.30,
    z: 0.03,  
  },
  detection_radius: 0.10,
  orientation_type: up_x
}


# These are locations where only the robot can build - Keeping a distance 15 cm between 
l0: {
  default: {
    x: 0.25,
    y: 0.40,
    z: 0.03,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


l1: {
  default: {
    x: 0.10,
    y: 0.40,
    z: 0.03, 
  },
  detection_radius: 0.10,
  orientation_type: up_x
}

l2: {
  default: {
    x: -0.05,
    y: 0.40,
    z: 0.03,
  },
  detection_radius: 0.10,
  orientation_type: up_x
}

l3: {
  default: {
    x: -0.20,
    y: 0.40,
    z: 0.03,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}

# Locations where only the robot and human can move objects
l6: {
  default: {
    x: -0.50,
    y: 0.40,
    z: 0.03,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


l7: {
  default: {
    x: -0.50,
    y: 0.25,
    z: 0.03,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


l8: {
  default: {
    x: -0.50,
    y: 0.10,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}

l9: {
  default: {
    x: -0.50,
    y: -0.05,
    z: 0.03,  
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}