location_names: 
  - "Else_1"
  - "Else_2"
  - "Else_3"
  - "HL0"
  - "HL1"
  - "HL2"
  - "HL3"
  - "L1"
  - "L2"
  - "L3"
  - "O1"
  - "O2"
  - "O3"

### else location where A1 and A3 are placed and I_1 is placed
Else_1: { 
  x: 0.40,
  y: 0.10,
  z: 0.03, 
  r: 0.10, 
}


Else_2: { 
  x: 0.60,
  y: 0.10,
  z: 0.03, 
  r: 0.10, 
}


Else_3: { 
  x: 0.50,
  y: 0.30,
  z: 0.03, 
  r: 0.10, 
}


# These are locations where the robot and Human can build - Keeping a distance 15 cm between 
HL0: { 
  x: 0.25,
  y: 0.40,
  z: 0.04, 
  r: 0.10, 
}


HL1: { 
  x: 0.10,
  y: 0.40,
  z: 0.04, 
  r: 0.10, 
}

HL2: { 
  x: -0.05,
  y: 0.40,
  z: 0.04, 
  r: 0.10, 
}

HL3: { 
  x: -0.20,
  y: 0.40,
  z: 0.04, 
  r: 0.10, 
}

# Locations where only the robot can move objects
L1: { 
  x: -0.50,
  y: 0.40,
  z: 0.04, 
  r: 0.10, 
}


L2: { 
  x: -0.50,
  y: 0.25,
  z: 0.04, 
  r: 0.10, 
}


L3: { 
  x: -0.50,
  y: -0.05,
  z: 0.04, 
  r: 0.10, 
}


# Locations where the static obstacles are placed
O1: { 
  x: -0.35,
  y: 0.40,
  z: 0.04, 
  r: 0.10, 
}

O2: { 
  x: -0.65,
  y: 0.40,
  z: 0.04, 
  r: 0.10, 
}


O3: { 
  x: -0.50,
  y: 0.10,
  z: 0.04, 
  r: 0.10, 
}

# affects how the hand approaches the empty location
location_orientation_types:
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
  - up_x
