location_names: 
  - "L0"
  - "L1"
  - "HL0"
  - "HL1"
  - "HL2"
  - "HL3"


L0: {
  default: {
    x: -0.05,
    y: 0.40,
    z: 0.075,
  },
  detection_radius: 0.10,
  orientation_type: up_x
}

L1: {
  default: {
    x: -0.20,
    y: 0.40,
    z: 0.075,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}

HL3: {
  default: {
    x: -0.50,
    y: 0.25,
    z: 0.075,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}



HL2: {
  default: {
    x: -0.50,
    y: 0.10,
    z: 0.075,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}

HL1: {
  default: {
    x: -0.50,
    y: -0.05,
    z: 0.075,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}

HL0: {
  default: {
    x: -0.50,
    y: -0.20,
    z: 0.075,  
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


