location_names: 
  - "Else_1"
  - "Else_2"
  - "Else_3"
  - "HL0"
  - "HL1"
  - "HL2"
  - "HL3"
  - "L1"
  - "L2"
  - "L3"
  - "O1"
  - "O2"
  - "O3"


### else location where A1 and A2 are placed and I_1 is placed
Else_1: {
  default: {
    x: 0.40,
    y: 0.10,
    z: 0.03, 
  },
  detection_radius: 0.10, 
  orientation_type: up_x
}

Else_2: {
  default: {
    x: 0.60,
    y: 0.10,
    z: 0.03, 
  },
  detection_radius: 0.10,
  orientation_type: up_x
}


Else_3: {
  default: {
    x: 0.50,
    y: 0.30,
    z: 0.03,  
  },
  detection_radius: 0.10,
  orientation_type: up_x
}


# These are locations where the robot and Human can build - Keeping a distance 15 cm between 
HL0: {
  default: {
    x: 0.25,
    y: 0.40,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


HL1: {
  default: {
    x: 0.10,
    y: 0.40,
    z: 0.04, 
  },
  detection_radius: 0.10,
  orientation_type: up_x
}

HL2: {
  default: {
    x: -0.05,
    y: 0.40,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x
}

HL3: {
  default: {
    x: -0.20,
    y: 0.40,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}

# Locations where only the robot can move objects
L1: {
  default: {
    x: -0.50,
    y: 0.40,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


L2: {
  default: {
    x: -0.50,
    y: 0.25,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


L3: {
  default: {
    x: -0.50,
    y: -0.05,
    z: 0.04,  
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}


# Locations where the static obstacles are placed
O1: {
  default: {
    x: -0.35,
    y: 0.40,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x
}

O2: {
  default: {
    x: -0.65,
    y: 0.40,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x
}


O3: {
  default: {
    x: -0.50,
    y: 0.10,
    z: 0.04,
  },
  detection_radius: 0.10,
  orientation_type: up_x 
}