location_names: 
  - "L1"
  - "L2"
  - "L3"
  - "L4"
  - "L5"

L1: { 
  x: 0.40,
  y: 0.20,
  z: 0.09, 
  r: 0.20, 
}

L2: { 
  x: 0.40,
  y: -0.20,
  z: 0.09, 
  r: 0.20, 
}

L3: { 
  x: -0.40,
  y: 0.20,
  z: 0.09, 
  r: 0.20, 
}

L4: { 
  x: -0.40,
  y: -0.20,
  z: 0.09, 
  r: 0.20, 
}

L5: { 
  x: 0.40,
  y: 0.00,
  z: 0.09, 
  r: 0.20, 
}


location_orientation_types:
  - up_x
  - up_x 
  - up_x
  - up_x 
  - up_x