object_ids:
  - groundrobot

groundrobot: {
  position: {
    x: 0.6,
    y: 0.0,
    z: -0.05,
  },
  dimensions: {
    length: 0.3,
    width: 0.7,
    height: 0.1,
  },
  primitive_type: box,
  orientation_type: up_x,
}