object_ids:
  - ground
  - dishwasher

ground: {
  position: {
    x: 0.0,
    y: 0.0,
    z: -0.05,
  },
  dimensions: {
    length: 1.5,
    width: 1.5,
    height: 0.1,
  },
  primitive_type: box,
  orientation_type: up_x,
}

dishwasher: {
  position: {
    x: 0.4,
    y: 0.0,
    z: 0.0775,
  },
  dimensions: {
    length: 0.27,
    width: 0.41,
    height: 0.155,
    base_thickness: 0.015,
    #base_thickness: 0.005,
    front_wall_thickness: 0.02,
    side_wall_thickness: 0.025,
  },
  primitive_type: bin,
  orientation_type: up_x
}